/*
-che cos'è il this in javascript
RISPOSTA:
- IL THIS È UN PARTICOLARE IDENTIFICATORE CON IL QUALE È POSSIBILE
FAR RIFERIMENTO A 'SE STESSO'. IN JAVASCRIPT IL THIS È UNA PAROLA CHIAVE CHE FA RIFERIMENTO A UN OGGETTO, QUALE OGGETTO 
DIPENDE DA COME THIS VIENE INVOCATO, USATO O CHIAMATO.
IN UN METODO OGGETTO, THIS FA RIFERIMENTO ALL OGGETTO,
DA SOLO, IL THIS SI RIFERISCE ALL OGGETTO GLOBALE, perchè THIS È IN ESECUZIONE NELL' AMBITO GLOBALE(WINDOW)
IN UNA FUNZIONE(IMPOSTAZIONE PREDEFINITA), THIS FA RIFERIMFIRMENTO ALL'OGGETTO GLOBALE(WINDOW)
IN UNA FUNZIONE IN MODALITÀ RIGOROSA, THIS È UNDEFINED
IN UN EVENTO, THIS SI RIFERISCE ALL'ELEMENTO CHE HA RICEVUTO L'EVENTO
*/